### ISSUE TITLE
Error while initializing Pyramid class with Telescope object not coupled with a Source

### ISSUE THREAD

**Issue by joao-aveiro** [cheritier/OOPAO#5]
### Description

When trying to instantiate the `Pyramid` class using a `Telescope` object which has not been coupled (i.e. `__mul__`) with a `Source` object, a non-descriptive error is raised in the `Pyramid.initialization()` method, resulting from the fact that `self.telescope.src.fluxMap`  is an empty list:

```Python
...
File "./OOPAO/OOPAO/Pyramid.py", line 923, in __mul__
    obj.frame = obj.frame *(self.telescope.src.fluxMap.sum())/obj.frame.sum()
AttributeError: 'list' object has no attribute 'sum'
```

While it is to be expected that instantiating the `Pyramid` class without a source coupled to the respective `Telescope` results in some sort of error, it would be helpful that a more descriptive message or exception is provided to the user. Alternatively, a check could be performed at the beginning of the `Pyramid` class init to guarantee that a source object is defined. More so, it should be noted that, by default, a placeholder source object is set as the `Telescope` source during initialization, though it is not coupled (i.e. `__mul__`) with the `Telescope` object, resulting in `src.fluxMaps` never being set.

### Fix

Some suggested changes include:

1. When coupling the `Pyramid` with the `Telescope`, check if there is a valid source (and non-null `Telescope.src.fluxMap`) coupled with the `Telescope` object;
2. When trying to compute the WFS signal and there is a coupled object missing (e.g. `Telescope` and/or `Telescope.src`), raise an informative exception (also probably implement custom exceptions);
3. Remove default `Source` from the `Telescope` initialization and block/raise exceptions (custom, if possible) when trying to access `Telescope` attributes or functions that cannot be computed without a source.

Though coupling the default `Source` object in the `Telescope` class would solve this issue, I believe this should be avoided since in case the user forgets to define and couple the source object or there is some problem coupling the source with the telescope, the simulation can still be run without the user noticing and possibly result in erroneous results.

**Comment by cheritier** [comment]
### **Answer**
I agree with the suggestion proposed, in particular to avoid 'hiding' that a default `Source` is created when the `Telescope` is initialized.
### **Modifications**

1. The `Telescope` class has been updated to set the default `src` object to `None`. 

2.  If a `Source` is not properly attached to the `Telescope `object, an error will be raised when initializing the objects that require a source object such as `Pyramid`, `Atmosphere` and `ShackHartmann` as well if the method `Telescope.computePSF()` is requested. In that case, there is no need to check that the `Telescope.src.fluxMap` is non-null.
